"use client";
import { FolderKanban, WalletCards } from "lucide-react";
import { useState } from "react";
import { useSystemUi } from "@/components/i18n/use-system-ui";
import { NumberField } from "@/components/common/number-field";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { addOnboardingProject } from "@/lib/onboarding-workspace";
import type { AppData } from "@/lib/types";
import { StepShell } from "./step-shell";
export function FreelancerProjectStep({ data, setData }: { data: AppData; setData: React.Dispatch<React.SetStateAction<AppData>> }) {
  const { s } = useSystemUi(); const [clientId, setClientId] = useState(data.clients.find((client) => !client.archived)?.id ?? ""); const [name, setName] = useState(""); const [rate, setRate] = useState(850_000); const [budgetHours, setBudgetHours] = useState(60); const [status, setStatus] = useState("");
  function saveProject() { if (!clientId) return setStatus(s("A client is required to create a project. Go back or skip this step.")); if (!name.trim()) return setStatus(s("Enter a project name or skip this step for now.")); const result = addOnboardingProject(data, { clientId, name, rate, budgetHours }); setData(result.data); setStatus(result.created ? s("The project is ready and its rate will be used by billable timers.") : s("This project already exists for the selected client.")); if (result.created) setName(""); }
  return <StepShell><div className="mx-auto mb-7 max-w-[700px] text-center"><span className="mx-auto mb-3 grid size-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent-strong)]"><FolderKanban /></span><h1>{s("Set up your first project and rate")}</h1><p>{s("Project rate is used to calculate timer income. Time budget powers near-limit warnings.")}</p></div><div className="mx-auto grid max-w-[820px] gap-4 rounded-[var(--card-radius)] border border-[var(--dashboard-border)] bg-[var(--surface-1)] p-4 text-start sm:grid-cols-2 sm:p-5" data-onboarding-freelancer-project data-onboarding-inline-form><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)] sm:col-span-2">{s("Client")}<Select value={clientId} onValueChange={setClientId} disabled={data.clients.length === 0}><SelectTrigger data-onboarding-project-client><SelectValue placeholder={data.clients.length ? s("Select a client") : s("No clients yet")} /></SelectTrigger><SelectContent>{data.clients.filter((client) => !client.archived).map((client) => <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)] sm:col-span-2">{s("Project name")}<Input data-onboarding-project-name value={name} onChange={(event) => setName(event.target.value)} placeholder={s("For example, Website design")} /></label><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)]">{s("Hourly rate")} <span className="font-normal">{s("Toman")}</span><NumberField data-onboarding-project-rate min={0} step={50_000} value={rate} onValueChange={setRate} /></label><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)]">{s("Time budget")} <span className="font-normal">{s("Hours")}</span><NumberField min={0} step={1} value={budgetHours} onValueChange={setBudgetHours} /></label><div className="flex flex-wrap items-center gap-2 sm:col-span-2"><Button type="button" data-onboarding-project-create onClick={saveProject} disabled={data.clients.length === 0}><WalletCards /> {s("Save project")}</Button><span className="text-[10px] leading-5 text-[var(--text-muted)]">{s("If you have many projects, CSV in the Import step is faster.")}</span></div>{status && <p role="status" className="text-[10px] font-semibold leading-5 text-[var(--accent-strong)] sm:col-span-2">{status}</p>}</div></StepShell>;
}
