"use client";
import { BriefcaseBusiness, CheckCircle2, UsersRound } from "lucide-react";
import { useState } from "react";
import { useSystemUi } from "@/components/i18n/use-system-ui";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { addOnboardingClient } from "@/lib/onboarding-workspace";
import type { AppData } from "@/lib/types";
import { StepShell } from "./step-shell";
export function FreelancerClientStep({ data, setData }: { data: AppData; setData: React.Dispatch<React.SetStateAction<AppData>> }) {
  const { s, number } = useSystemUi(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [status, setStatus] = useState("");
  function saveClient() { const trimmed = name.trim(); if (!trimmed) return setStatus(s("Enter a client name or skip this step for now.")); const result = addOnboardingClient(data, { name: trimmed, email }); setData(result.data); setStatus(result.created ? s("Your first client is ready. You can create its project next.") : s("This client already existed and was not created again.")); setName(""); setEmail(""); }
  return <StepShell><div className="mx-auto mb-7 max-w-[700px] text-center"><span className="mx-auto mb-3 grid size-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent-strong)]"><UsersRound /></span><h1>{s("Prepare your first client")}</h1><p>{s("For freelance work, a client is the starting point for projects, billable time, and invoices. This step is optional.")}</p></div><div className="mx-auto grid max-w-[760px] gap-4 rounded-[var(--card-radius)] border border-[var(--dashboard-border)] bg-[var(--surface-1)] p-4 text-start sm:p-5" data-onboarding-freelancer-client data-onboarding-inline-form><div className="flex items-center justify-between gap-3"><div><strong className="text-sm text-[var(--text)]">{s("First client")}</strong><p className="mt-1 text-[10px] leading-5 text-[var(--text-muted)]">{s("If you already have clients, you can import them all at once in the Import step.")}</p></div><span className="inline-flex items-center gap-1 rounded-xl bg-[var(--surface-2)] px-3 py-2 text-[10px] font-bold text-[var(--text-muted)]"><BriefcaseBusiness className="size-3.5" /> {s("{count} clients", { count: number(data.clients.length) })}</span></div><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)]">{s("Client name")}<Input data-onboarding-client-name value={name} onChange={(event) => setName(event.target.value)} placeholder={s("For example, Alpha Studio")} /></label><label className="grid gap-2 text-[11px] font-bold text-[var(--text-muted)]">{s("Email")} <span className="font-normal">({s("Optional")})</span><Input value={email} onChange={(event) => setEmail(event.target.value)} inputMode="email" placeholder="hello@example.com" /></label><div className="flex flex-wrap items-center gap-2"><Button type="button" data-onboarding-client-create onClick={saveClient}>{s("Save client")}</Button><span className="text-[10px] text-[var(--text-muted)]">{s("You can continue without creating a client.")}</span></div>{status && <p role="status" className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-[var(--accent-strong)]"><CheckCircle2 className="size-3.5" /> {status}</p>}</div></StepShell>;
}
