import type React from "react";
import type { ReturnTypeCalc } from "@/lib/type-helpers";
import type { ActivityKind, ActivitySegment, AppData, BreakItem, ClientDraft, ProjectDraft, Tab, TimeEntry, TimerDraft, WorkRecord, WorkRecordPatch } from "@/lib/types";
import type { ProjectTimerSession } from "@/lib/project-timer-session";

export type TodayPageProps = {
  data: AppData;
  setToast: (message: string) => void;
  record: WorkRecord;
  selectedDate: string;
  setSelectedDate: (date: string) => void;
  todayCalc: ReturnTypeCalc;
  dailyTarget: number;
  suggestedExit: string;
  activeEntry?: TimeEntry;
  projectTimerSession: ProjectTimerSession | null;
  activeBreak?: BreakItem;
  activeActivitySegment?: ActivitySegment;
  lunchRunning: boolean;
  timerDraft: TimerDraft;
  setTimerDraft: React.Dispatch<React.SetStateAction<TimerDraft>>;
  startWork: () => void;
  resumeAutoClosedWork: () => void;
  pendingPreviousRecord?: WorkRecord;
  closePreviousAndStart: () => void;
  reviewPreviousRecord: () => void;
  dismissPreviousRecord: () => void;
  finishWork: () => void;
  updateRecord: (patch: WorkRecordPatch) => void;
  resetRecord: () => void;
  resetUndoDate?: string;
  undoResetRecord: () => void;
  dismissResetUndo: () => void;
  startLunch: () => void;
  finishLunch: () => void;
  startBreak: () => void;
  finishBreak: (minutes?: number) => void;
  startActivitySegment: (kind: ActivityKind, projectId?: string) => void;
  stopActivitySegment: () => void;
  toggleProjectTimer: (projectId?: string) => void;
  startProjectTimer: (projectId?: string) => void;
  pauseProjectTimer: () => void;
  resumeProjectTimer: () => void;
  finishProjectTimer: () => void;
  updateProjectTimerDetails: (patch: Partial<Pick<TimeEntry, "task" | "note" | "billable">>) => void;
  createClient: (draft: ClientDraft) => string | undefined;
  createProject: (draft: ProjectDraft) => string | undefined;
  editingEntry: string;
  setEditingEntry: (id: string) => void;
  setData: React.Dispatch<React.SetStateAction<AppData>>;
  setTab: (tab: Tab) => void;
  financialsHidden: boolean;
};
