import { ChevronRight, Clock3, Info, Pause, Play, Square, Tag, TrendingUp, WalletCards } from "lucide-react";
import { EmptyState } from "@/components/common/empty-state";
import { MetricCard } from "@/components/common/metric-card";
import { PanelHead } from "@/components/common/panel-head";
import { StatusBadge } from "@/components/common/status-badge";
import { Button } from "@/components/ui/button";
import { duration, entryMinutes, fa, money } from "@/lib/format";
import type { AppData, Project, TimeEntry } from "@/lib/types";
import { cn } from "@/lib/cn";

export function ProjectDetail({ data, setData, project, activeEntry, onBack, onToggleTimer, financialsHidden }: {
  data: AppData;
  setData: React.Dispatch<React.SetStateAction<AppData>>;
  project: Project;
  activeEntry?: TimeEntry;
  onBack: () => void;
  onToggleTimer: (id?: string) => void;
  financialsHidden: boolean;
}) {
  const entries = data.timeEntries.filter((entry) => entry.projectId === project.id);
  const minutes = entries.reduce((sum, entry) => sum + entryMinutes(entry), 0);
  const billable = entries.filter((entry) => entry.billable).reduce((sum, entry) => sum + entryMinutes(entry), 0);
  const progress = Math.min(100, Math.round(minutes / Math.max(1, (project.budgetHours ?? 0) * 60) * 100));
  return <>
    <section className={cn("mb-[22px] flex min-h-24 items-start justify-between gap-6 [&>div:first-child]:min-w-0 [&_h1]:mb-0.5 [&_h1]:mt-2 [&_h1]:text-[clamp(26px,2.4vw,36px)] [&_h1]:leading-[1.35] [&_h1]:tracking-[-.9px] [&_p]:m-0 [&_p]:text-[13px] [&_p]:text-[#6c7d89] max-[620px]:mb-[17px] max-[620px]:min-h-0 max-[620px]:flex-col max-[620px]:[&>button]:w-full max-[620px]:[&>.row-actions]:w-full max-[620px]:[&_.date-popover]:w-full max-[620px]:[&_h1]:text-[25px]", "[&_h1]:flex [&_h1]:items-center [&_h1]:gap-[10px] [&_h1_i]:h-[35px] [&_h1_i]:w-3 [&_h1_i]:rounded-[7px]")}><div><button type="button" className={cn("flex items-center gap-1 border-0 bg-transparent p-0 text-[#079b60]")} onClick={onBack}><ChevronRight /> همه پروژه‌ها</button><h1><i style={{ background: project.color }} />{project.name}</h1><p>کارفرما: {data.clients.find((client) => client.id === project.clientId)?.name}</p></div><div className={cn("flex items-center gap-[9px] max-[620px]:flex-wrap")}><Button onClick={() => onToggleTimer(project.id)}>{activeEntry?.projectId === project.id ? <><Square /> پایان تایمر</> : <><Play /> شروع تایمر</>}</Button><Button variant="outline" onClick={() => setData((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, status: item.status === "active" ? "paused" : "active" } : item) }))}><Pause /> {project.status === "active" ? "توقف پروژه" : "فعال‌سازی"}</Button></div></section>
    <section className={cn("mb-[18px] grid gap-3", "grid-cols-4 max-[1180px]:grid-cols-2 max-[620px]:grid-cols-1")}><MetricCard icon={<Clock3 />} label="زمان ثبت‌شده" value={duration(minutes)} suffix="ساعت" /><MetricCard icon={<TrendingUp />} label="بودجه زمانی" value={`${fa.format(progress)}٪`} suffix={`از ${fa.format(project.budgetHours ?? 0)} ساعت`} /><MetricCard icon={<WalletCards />} label="مبلغ قابل صورتحساب" value={financialsHidden ? "••••••" : money(billable / 60 * project.rate)} suffix="تومان" /><MetricCard icon={<Tag />} label="نرخ ساعتی" value={financialsHidden ? "••••••" : money(project.rate)} suffix="تومان" tone="blue" /></section>
    <section className={cn("mb-[18px] grid grid-cols-[190px_1fr_230px] items-center gap-7 px-6 py-[18px] [&>div]:grid [&>div]:gap-1 [&>div:not(.progress-main)]:text-center [&_span]:text-[10px] [&_span]:text-[#6c7d89] [&_small]:text-[10px] [&_small]:text-[#6c7d89] [&_strong]:text-[22px] [&_strong]:text-[#079b60] max-[900px]:grid-cols-1 max-[900px]:[&_.progress-main]:row-start-1", "rounded-[15px] border border-[#dfe7e9] bg-white/95 shadow-[0_10px_35px_rgba(17,45,55,.055)] p-4")}><div><span>باقی‌مانده</span><strong>{duration(Math.max(0, (project.budgetHours ?? 0) * 60 - minutes))}</strong></div><div className={cn("[&>i]:my-2 [&>i]:block [&>i]:h-[7px] [&>i]:overflow-hidden [&>i]:rounded-[10px] [&>i]:bg-[#e8edef] [&>i>b]:block [&>i>b]:h-full [&>i>b]:rounded-[inherit] [&>i>b]:bg-[#079b60]")}><span>بودجه زمانی پروژه</span><i><b style={{ width: `${progress}%` }} /></i><small>{duration(minutes)} از {fa.format(project.budgetHours ?? 0)} ساعت</small></div><div><span>هزینه مورد انتظار</span><strong>{financialsHidden ? "••••••" : money((project.budgetHours ?? 0) * project.rate)}</strong><small>تومان</small></div></section>
    <section className={cn("grid grid-cols-[minmax(0,1fr)_320px] gap-[14px] max-[900px]:grid-cols-1", "grid-cols-[minmax(0,1fr)_250px] max-[900px]:grid-cols-1")}><article className={cn("rounded-[15px] border border-[#dfe7e9] bg-white/95 shadow-[0_10px_35px_rgba(17,45,55,.055)] p-4", "min-w-0 p-[13px]")}><PanelHead icon={<Clock3 />} title="تازه‌ترین رکوردهای زمان" /><div className={cn("w-full overflow-x-auto [&_table]:w-full [&_table]:border-collapse [&_table]:text-[11px] [&_th]:h-[39px] [&_th]:whitespace-nowrap [&_th]:border-y [&_th]:border-[#edf1f2] [&_th]:bg-[#fbfcfc] [&_th]:px-3 [&_th]:py-2 [&_th]:text-right [&_th]:font-semibold [&_th]:text-[#536975] [&_td]:min-h-[46px] [&_td]:whitespace-nowrap [&_td]:border-b [&_td]:border-[#edf1f2] [&_td]:px-3 [&_td]:py-[9px] [&_td]:text-[#2e4856] [&_td_strong]:flex [&_td_strong]:items-center [&_td_strong]:gap-[7px] [&_td_strong]:text-[11px] [&_td_strong]:text-[#102a3a] [&_td_strong>i]:h-[7px] [&_td_strong>i]:w-[7px] [&_td_strong>i]:rounded-full [&_td_small]:mt-[3px] [&_td_small]:block [&_td_small]:text-[9px] [&_td_small]:text-[#6c7d89] [&_td_input]:min-w-[175px]")}><table><thead><tr><th>تاریخ</th><th>شروع</th><th>پایان</th><th>مدت</th><th>وظیفه</th><th>قابل صورتحساب</th></tr></thead><tbody>{entries.slice(0, 8).map((entry) => <tr key={entry.id}><td>{new Intl.DateTimeFormat("fa-IR-u-ca-persian", { weekday: "long", day: "numeric", month: "long" }).format(new Date(entry.startedAt))}</td><td>{new Date(entry.startedAt).toLocaleTimeString("fa-IR", { hour: "2-digit", minute: "2-digit" })}</td><td>{entry.endedAt ? new Date(entry.endedAt).toLocaleTimeString("fa-IR", { hour: "2-digit", minute: "2-digit" }) : "در حال اجرا"}</td><td>{duration(entryMinutes(entry))}</td><td>{entry.task || entry.note || "—"}</td><td><StatusBadge success={entry.billable}>{entry.billable ? "بله" : "خیر"}</StatusBadge></td></tr>)}{entries.length === 0 && <tr><td colSpan={6}><EmptyState compact icon={<Clock3 />} description="هنوز زمانی برای این پروژه ثبت نشده." /></td></tr>}</tbody></table></div></article><aside className={cn("rounded-[15px] border border-[#dfe7e9] bg-white/95 shadow-[0_10px_35px_rgba(17,45,55,.055)] p-4", "max-[900px]:order-first [&_dl]:m-0 [&_dl>*]:block [&_dt]:border-t [&_dt]:border-[#edf1f2] [&_dt]:pt-[13px] [&_dt]:text-[10px] [&_dt]:text-[#6c7d89] [&_dd]:mb-[13px] [&_dd]:mt-1.5 [&_dd]:text-xs")}><PanelHead icon={<Info />} title="اطلاعات پروژه" /><dl><dt>وضعیت</dt><dd><StatusBadge success>{project.status === "active" ? "فعال" : "متوقف"}</StatusBadge></dd><dt>واحد پول</dt><dd>تومان</dd><dt>قابل صورتحساب</dt><dd>{project.billable === false ? "خیر" : "بله"}</dd><dt>یادداشت‌ها</dt><dd>{project.note || "—"}</dd></dl></aside></section>
  </>;
}
