import { useSystemUi } from "@/components/i18n/use-system-ui";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { CSV_IMPORT_FIELDS, type CsvImportKind, type CsvMapping } from "@/lib/import-wizard";
import type { SystemMessageKey } from "@/lib/i18n/system";
const FIELD_KEYS: Record<string, SystemMessageKey> = { date: "Date", start: "Clock in", end: "Clock out", lunchMinutes: "Lunch (minutes)", note: "Note", holiday: "Holiday", name: "Client name", email: "Email", archived: "Archived", client: "Client", rate: "Rate", budgetHours: "Budget hours", status: "Status", billable: "Billable", title: "Title", amount: "Amount", project: "Project", category: "Category" };
export function CsvMappingGrid({ kind, headers, mapping, onChange }: { kind: CsvImportKind; headers: string[]; mapping: CsvMapping; onChange: (field: string, header: string) => void }) {
  const { s } = useSystemUi();
  return <div className="grid gap-3 sm:grid-cols-2" data-import-mapping>{CSV_IMPORT_FIELDS[kind].map((field) => { const label = s(FIELD_KEYS[field.key] ?? "Item"); return <label key={field.key} className="grid gap-1.5 rounded-xl border border-[var(--dashboard-border)] bg-[var(--surface-2)] p-3 text-[11px] font-semibold text-[var(--text-muted)]"><span>{label}{field.required && <span className="ms-1 text-[var(--danger)]">*</span>}</span><Select value={mapping[field.key] || "__ignore__"} onValueChange={(value) => onChange(field.key, value === "__ignore__" ? "" : value)}><SelectTrigger aria-label={s("Column {field}", { field: label })}><SelectValue placeholder={s("Select column")} /></SelectTrigger><SelectContent><SelectItem value="__ignore__">{s("Ignore")}</SelectItem>{headers.map((header) => <SelectItem key={header} value={header}>{header}</SelectItem>)}</SelectContent></Select></label>; })}</div>;
}
