import { cn } from "./cn";

type Token = string | false | null | undefined;

const surface = "rounded-[15px] border border-[#dfe7e9] bg-white/95 shadow-[0_10px_35px_rgba(17,45,55,.055)]";
const panelHead = "mb-3 flex min-h-[37px] items-start justify-between gap-3 [&>div:first-child]:flex [&>div:first-child]:items-center [&>div:first-child]:gap-2 [&_h2]:m-0 [&_h2]:text-[15px] [&_svg]:text-[#079b60]";
const fieldGrid = "[&_label]:grid [&_label]:gap-[7px] [&_label]:text-[11px] [&_label]:font-semibold [&_label]:text-[#314b58]";

export const styles: Record<string, string> = {
  "app-shell": `min-h-screen w-full p-3 max-[900px]:p-[7px] max-[900px]:pb-24 ${fieldGrid} [&_button]:cursor-pointer [&_svg]:h-[18px] [&_svg]:w-[18px] [&_svg]:stroke-[1.85]`,
  workspace: "mx-auto max-w-[1510px] px-[26px] pb-[18px] pt-[30px] max-[900px]:px-[10px] max-[900px]:py-[22px]",
  loading: "grid min-h-screen place-content-center gap-3 font-extrabold text-[#079b60] [&_svg]:mx-auto [&_svg]:h-8 [&_svg]:w-8",
  topbar: "sticky top-[10px] z-40 grid min-h-[72px] grid-cols-[280px_1fr_330px] items-center gap-[18px] rounded-2xl border border-[#dfe7e9] bg-white/95 px-6 shadow-[0_7px_26px_rgba(30,65,74,.04)] backdrop-blur-2xl max-[1180px]:grid-cols-[220px_1fr_auto] max-[1180px]:px-[15px] max-[900px]:static max-[900px]:grid-cols-[1fr_auto] max-[620px]:min-h-16 max-[620px]:rounded-[13px] max-[620px]:px-[10px]",
  brand: "flex items-center gap-[11px] [&>span]:grid [&>span]:h-11 [&>span]:w-11 [&>span]:place-items-center [&>span]:rounded-full [&>span]:border-[3px] [&>span]:border-[#079b60] [&>span]:text-[#079b60] [&>span_svg]:h-[25px] [&>span_svg]:w-[25px] [&>div]:grid [&>div]:leading-tight [&_strong]:text-[23px] [&_strong]:tracking-[-.6px] [&_small]:mt-1 [&_small]:text-[10px] [&_small]:text-[#6c7d89] max-[900px]:[&_small]:hidden max-[620px]:[&>span]:h-9 max-[620px]:[&>span]:w-9 max-[620px]:[&>span_svg]:h-5 max-[620px]:[&>span_svg]:w-5 max-[620px]:[&_strong]:text-lg",
  "main-nav": "flex h-[71px] justify-center gap-5 max-[1180px]:gap-[5px] max-[900px]:fixed max-[900px]:inset-x-[7px] max-[900px]:bottom-[7px] max-[900px]:!top-auto max-[900px]:z-50 max-[900px]:h-16 max-[900px]:justify-around max-[900px]:rounded-[15px] max-[900px]:border max-[900px]:border-[#dfe7e9] max-[900px]:bg-white/95 max-[900px]:p-1 max-[900px]:shadow-[0_-8px_30px_rgba(17,45,55,.08)] [&_button]:relative [&_button]:inline-flex [&_button]:min-w-[86px] [&_button]:items-center [&_button]:justify-center [&_button]:gap-2 [&_button]:border-0 [&_button]:bg-transparent [&_button]:font-bold [&_button]:text-[#102a3a] [&_button.active]:text-[#079b60] [&_button]:after:absolute [&_button]:after:inset-x-3 [&_button]:after:bottom-0 [&_button]:after:h-[3px] [&_button]:after:rounded-t-lg [&_button]:after:content-[''] [&_button.active]:after:bg-[#079b60] max-[1180px]:[&_button]:min-w-[72px] max-[900px]:[&_button]:min-w-[55px] max-[900px]:[&_button]:flex-col max-[900px]:[&_button]:gap-[3px] max-[900px]:[&_button]:text-[9px] max-[900px]:[&_button]:after:bottom-[-4px]",
  "top-actions": "flex items-center justify-end gap-[9px] max-[900px]:[&>button:last-child]:h-11 max-[900px]:[&>button:last-child]:w-11 max-[900px]:[&>button:last-child]:overflow-hidden max-[900px]:[&>button:last-child]:text-[0px] max-[620px]:[&>button:first-of-type]:hidden",
  "quick-mode-switch": "grid h-12 grid-cols-[auto_112px] items-center gap-2 rounded-xl border border-[#cfe2dc] bg-[#edf9f4] py-[5px] pl-[10px] pr-[7px] [&>span]:inline-flex [&>span]:items-center [&>span]:gap-[5px] [&>span]:whitespace-nowrap [&>span]:text-[10px] [&>span]:font-bold [&>span]:text-[#316153] [&>span_svg]:h-[15px] [&>span_svg]:w-[15px] [&>span_svg]:text-[#079b60] max-[1180px]:grid-cols-[105px] max-[1180px]:p-[5px] max-[1180px]:[&>span]:hidden max-[620px]:w-[104px] max-[620px]:grid-cols-1",
  autosave: "inline-flex items-center gap-1.5 text-xs font-semibold text-[#079b60] [&_svg]:h-[15px] [&_svg]:w-[15px] max-[1180px]:hidden",
  "save-inline": "inline-flex items-center gap-1.5 text-xs font-semibold text-[#079b60] [&_svg]:h-[15px] [&_svg]:w-[15px]",
  "safe-note": "inline-flex items-center gap-1.5 text-xs font-semibold text-[#079b60] [&_svg]:h-[15px] [&_svg]:w-[15px] max-[620px]:hidden",
  "page-heading": "mb-[22px] flex min-h-24 items-start justify-between gap-6 [&>div:first-child]:min-w-0 [&_h1]:mb-0.5 [&_h1]:mt-2 [&_h1]:text-[clamp(26px,2.4vw,36px)] [&_h1]:leading-[1.35] [&_h1]:tracking-[-.9px] [&_p]:m-0 [&_p]:text-[13px] [&_p]:text-[#6c7d89] max-[620px]:mb-[17px] max-[620px]:min-h-0 max-[620px]:flex-col max-[620px]:[&>button]:w-full max-[620px]:[&>.row-actions]:w-full max-[620px]:[&_.date-popover]:w-full max-[620px]:[&_h1]:text-[25px]",
  "row-actions": "flex items-center gap-[9px] max-[620px]:flex-wrap",
  panel: `${surface} p-4`,
  "focus-card": `${surface} mb-[18px] grid grid-cols-[1fr_390px] gap-[26px] px-6 py-[19px] max-[1180px]:grid-cols-[1fr_330px] max-[900px]:grid-cols-1 max-[620px]:p-[15px]`,
  "metric-card": `${surface} flex min-h-28 items-center gap-4 px-[23px] py-[18px] [&>div]:grid [&>div]:min-w-0 [&>div]:gap-0.5 [&_small]:text-[11px] [&_small]:text-[#6c7d89] [&_strong]:whitespace-nowrap [&_strong]:text-[clamp(21px,2vw,30px)] [&_strong]:text-[#102a3a] [&>div>span]:text-[10px] [&>div>span]:text-[#6c7d89] max-[620px]:min-h-24`,
  "time-edit-strip": `${surface} mb-[18px] grid grid-cols-[1fr_1fr_1.2fr_1.5fr] gap-3 p-[13px] max-[900px]:grid-cols-2 max-[620px]:grid-cols-1`,
  "project-card": `${surface} p-[18px] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_16px_40px_rgba(17,45,55,.09)]`,
  "panel-head": panelHead,
  full: "w-full",
  "span-2": "col-span-2 max-[620px]:col-auto",
  "focus-form": "grid grid-cols-3 content-center gap-x-[18px] gap-y-[14px] max-[900px]:grid-cols-2 max-[620px]:grid-cols-1",
  "focus-note": "col-span-2 max-[620px]:col-auto",
  "billable-toggle": "self-end flex h-11 items-center justify-center gap-[9px] rounded-[11px] border border-[#dfe7e9] bg-white text-[#6c7d89] [&>span]:relative [&>span]:h-[22px] [&>span]:w-[38px] [&>span]:rounded-full [&>span]:bg-[#d7e0e2] [&>span]:after:absolute [&>span]:after:right-[3px] [&>span]:after:top-[3px] [&>span]:after:h-4 [&>span]:after:w-4 [&>span]:after:rounded-full [&>span]:after:bg-white [&>span]:after:transition-all [&>span]:after:content-['']",
  on: "text-[#102a3a] [&>span]:bg-[#079b60] [&>span]:after:right-[19px]",
  "focus-clock": "grid min-h-[170px] place-items-center content-center border-r border-[#dfe7e9] pr-[25px] text-center [&>strong]:my-[3px] [&>strong]:text-[clamp(31px,3.2vw,48px)] [&>strong]:font-medium [&>strong]:tracking-[1px] [&>small]:text-[#6c7d89] [&>div]:mt-[18px] [&>div]:flex [&>div]:gap-2 max-[900px]:border-0 max-[900px]:border-t max-[900px]:border-[#dfe7e9] max-[900px]:px-0 max-[900px]:pt-5 max-[620px]:[&>div]:w-full max-[620px]:[&>div]:flex-col",
  "running-label": "flex items-center gap-[7px] text-[11px] [&_i]:h-[9px] [&_i]:w-[9px] [&_i]:rounded-full [&_i]:bg-[#079b60] [&_i]:shadow-[0_0_0_5px_#e4f6ef]",
  "tracker-box": "flex items-center justify-between gap-[10px] rounded-[11px] border border-[#edf1f2] bg-[#fbfdfc] px-[10px] [&>span]:flex [&>span]:items-center [&>span]:gap-[7px] [&>span]:text-xs [&>span]:font-bold [&_small]:font-medium [&_small]:text-[#6c7d89] max-[620px]:min-h-[58px]",
  "preset-row": "flex gap-1",
  "metric-grid": "mb-[18px] grid gap-3",
  four: "grid-cols-4 max-[1180px]:grid-cols-2 max-[620px]:grid-cols-1",
  three: "grid-cols-3 max-[620px]:grid-cols-1",
  "metric-icon": "grid h-[52px] w-[52px] flex-none place-items-center rounded-full bg-[#edf9f4] text-[#079b60] [&_svg]:h-[26px] [&_svg]:w-[26px]",
  "tone-blue": "[&_.metric-icon]:bg-[#edf3ff] [&_.metric-icon]:text-[#276bd5]",
  "tone-amber": "[&_.metric-icon]:bg-[#fff6e5] [&_.metric-icon]:text-[#eaa21b]",
  "tone-purple": "[&_.metric-icon]:bg-[#f4efff] [&_.metric-icon]:text-[#7a58b8]",
  "goal-card": "justify-center [&>div:last-child_strong]:text-lg [&>div:last-child_strong_span]:text-[11px] [&>div:last-child_strong_span]:font-medium [&>div:last-child_strong_span]:text-[#6c7d89]",
  "mini-ring": "relative grid h-[72px] w-[72px] place-items-center rounded-full bg-[conic-gradient(#079b60_var(--p),#e6f0ed_0)] before:absolute before:inset-[7px] before:rounded-full before:bg-white before:content-[''] [&_strong]:relative [&_strong]:z-[1] [&_strong]:text-lg",
  "dashboard-grid": "grid grid-cols-[minmax(0,1fr)_320px] gap-[14px] max-[900px]:grid-cols-1",
  "timeline-panel": "min-w-0 p-[13px]",
  "table-panel": "min-w-0 p-[13px]",
  "table-wrap": "w-full overflow-x-auto [&_table]:w-full [&_table]:border-collapse [&_table]:text-[11px] [&_th]:h-[39px] [&_th]:whitespace-nowrap [&_th]:border-y [&_th]:border-[#edf1f2] [&_th]:bg-[#fbfcfc] [&_th]:px-3 [&_th]:py-2 [&_th]:text-right [&_th]:font-semibold [&_th]:text-[#536975] [&_td]:min-h-[46px] [&_td]:whitespace-nowrap [&_td]:border-b [&_td]:border-[#edf1f2] [&_td]:px-3 [&_td]:py-[9px] [&_td]:text-[#2e4856] [&_td_strong]:flex [&_td_strong]:items-center [&_td_strong]:gap-[7px] [&_td_strong]:text-[11px] [&_td_strong]:text-[#102a3a] [&_td_strong>i]:h-[7px] [&_td_strong>i]:w-[7px] [&_td_strong>i]:rounded-full [&_td_small]:mt-[3px] [&_td_small]:block [&_td_small]:text-[9px] [&_td_small]:text-[#6c7d89] [&_td_input]:min-w-[175px]",
  "table-total": "flex justify-center px-0 pb-0 pt-3 text-[11px] text-[#6c7d89] [&_strong]:text-base [&_strong]:text-[#102a3a]",
  status: "inline-flex items-center justify-center rounded-lg border border-[#d7dfe2] bg-[#f7f9f9] px-[9px] py-1 text-[10px] text-[#677984]",
  success: "border-[#caeade] bg-[#eff9f5] text-[#087e50]",
  "recent-projects": "p-[17px] max-[900px]:order-first [&>button]:mt-3",
  "recent-project": "grid grid-cols-[9px_1fr_auto] items-center gap-[10px] border-b border-[#edf1f2] py-3 [&>span]:h-[9px] [&>span]:w-[9px] [&>span]:rounded-full [&>div]:grid [&_strong]:text-xs [&_small]:text-[9px] [&_small]:text-[#6c7d89]",
  "long-timer-warning": "mt-[14px] flex items-center gap-[13px] rounded-[14px] border border-[#f1c36c] bg-[#fff9eb] px-[19px] py-[14px] text-[#8b5a05] [&>svg]:h-[27px] [&>svg]:w-[27px] [&>div]:grid [&>div]:flex-1 [&_span]:text-[10px] [&_span]:text-[#78694c] print:hidden",
  "inline-form": "mb-[18px] p-[18px]",
  "form-grid": "mb-4 grid gap-[14px]",
  two: "grid-cols-2 max-[620px]:grid-cols-1",
  "clients-layout": "grid-cols-[minmax(0,1fr)_365px] max-[1180px]:grid-cols-[minmax(0,1fr)_280px] max-[900px]:grid-cols-1",
  "search-box": "flex min-w-[230px] items-center gap-[7px] rounded-[11px] border border-[#dfe7e9] bg-white px-[10px] [&_svg]:flex-none [&_svg]:text-[#6c7d89] [&_input]:border-0 [&_input]:px-0 [&_input]:shadow-none",
  "avatar-name": "[&>span]:grid [&>span]:h-[39px] [&>span]:w-[39px] [&>span]:place-items-center [&>span]:rounded-full [&>span]:text-[17px] [&>span]:text-white",
  "top-clients": "p-5 max-[900px]:order-first",
  "bar-item": "py-3 [&>div]:flex [&>div]:justify-between [&>div]:gap-3 [&_strong]:text-xs [&_span]:text-[9px] [&_span]:text-[#6c7d89] [&_small]:text-[9px] [&_small]:text-[#6c7d89] [&>i]:my-2 [&>i]:block [&>i]:h-[7px] [&>i]:overflow-hidden [&>i]:rounded-[10px] [&>i]:bg-[#e8edef] [&>i>b]:block [&>i>b]:h-full [&>i>b]:rounded-[inherit] [&>i>b]:bg-[#079b60]",
  "project-cards": "grid grid-cols-3 gap-[14px] max-[1180px]:grid-cols-2 max-[620px]:grid-cols-1",
  "project-card-head": "grid grid-cols-[10px_1fr_auto] items-center gap-[10px] [&>span:first-child]:h-9 [&>span:first-child]:w-[10px] [&>span:first-child]:rounded-lg [&>div]:grid [&_strong]:text-[15px] [&_small]:text-[10px] [&_small]:text-[#6c7d89]",
  "project-card-stats": "my-5 grid grid-cols-2 gap-[10px] [&_span]:grid [&_span]:gap-[5px] [&_span]:rounded-[10px] [&_span]:bg-[#f8fbfa] [&_span]:p-[11px] [&_span]:text-[10px] [&_span]:text-[#6c7d89] [&_strong]:text-base [&_strong]:text-[#102a3a]",
  "budget-line": "mb-4 [&>div]:flex [&>div]:justify-between [&>div]:text-[10px] [&>i]:my-2 [&>i]:block [&>i]:h-[7px] [&>i]:overflow-hidden [&>i]:rounded-[10px] [&>i]:bg-[#e8edef] [&>i>b]:block [&>i>b]:h-full [&>i>b]:rounded-[inherit] [&>i>b]:bg-[#079b60]",
  "project-title": "[&_h1]:flex [&_h1]:items-center [&_h1]:gap-[10px] [&_h1_i]:h-[35px] [&_h1_i]:w-3 [&_h1_i]:rounded-[7px]",
  "back-link": "flex items-center gap-1 border-0 bg-transparent p-0 text-[#079b60]",
  "project-progress": "mb-[18px] grid grid-cols-[190px_1fr_230px] items-center gap-7 px-6 py-[18px] [&>div]:grid [&>div]:gap-1 [&>div:not(.progress-main)]:text-center [&_span]:text-[10px] [&_span]:text-[#6c7d89] [&_small]:text-[10px] [&_small]:text-[#6c7d89] [&_strong]:text-[22px] [&_strong]:text-[#079b60] max-[900px]:grid-cols-1 max-[900px]:[&_.progress-main]:row-start-1",
  "progress-main": "[&>i]:my-2 [&>i]:block [&>i]:h-[7px] [&>i]:overflow-hidden [&>i]:rounded-[10px] [&>i]:bg-[#e8edef] [&>i>b]:block [&>i>b]:h-full [&>i>b]:rounded-[inherit] [&>i>b]:bg-[#079b60]",
  "project-detail-grid": "grid-cols-[minmax(0,1fr)_250px] max-[900px]:grid-cols-1",
  "project-info": "max-[900px]:order-first [&_dl]:m-0 [&_dl>*]:block [&_dt]:border-t [&_dt]:border-[#edf1f2] [&_dt]:pt-[13px] [&_dt]:text-[10px] [&_dt]:text-[#6c7d89] [&_dd]:mb-[13px] [&_dd]:mt-1.5 [&_dd]:text-xs",
  filters: "mb-4 grid grid-cols-[1.2fr_repeat(3,1fr)_auto] gap-[11px] print:hidden max-[1180px]:grid-cols-2 max-[1180px]:[&_.search-box]:col-span-2 max-[620px]:grid-cols-1 max-[620px]:[&_.search-box]:col-auto",
  "charts-grid": "mb-[14px] grid grid-cols-[minmax(0,1.7fr)_minmax(280px,.55fr)] gap-[14px] max-[900px]:grid-cols-1",
  "chart-card": "min-h-[310px] p-[18px]",
  "dual-chart": "flex h-[215px] items-end justify-around gap-3 border-b border-[#dfe7e9] bg-[repeating-linear-gradient(to_top,transparent_0_44px,#eef2f2_45px)] px-4 pb-0 pt-5 [&>div]:relative [&>div]:flex [&>div]:h-full [&>div]:flex-1 [&>div]:items-end [&>div]:justify-center [&>div]:gap-[5px] [&_i]:min-h-1 [&_i]:w-[14px] [&_i]:rounded-t max-[620px]:gap-1 max-[620px]:px-0 max-[620px]:[&_i]:w-[9px] max-[620px]:[&_span]:-rotate-[35deg]",
  income: "bg-gradient-to-b from-[#3d83ec] to-[#276bd5]",
  time: "bg-gradient-to-b from-[#17ae6e] to-[#078b57]",
  "chart-note": "mt-7 block text-center text-[#6c7d89]",
  "donut-card": "grid place-items-center [&_.panel-head]:w-full [&_ul]:mt-[15px] [&_ul]:w-full [&_ul]:list-none [&_ul]:p-0 [&_li]:flex [&_li]:items-center [&_li]:gap-[7px] [&_li]:p-[5px] [&_li]:text-[10px] [&_li]:text-[#6c7d89] [&_li_i]:h-[7px] [&_li_i]:w-[7px] [&_li_i]:rounded-full [&_li_strong]:mr-auto [&_li_strong]:text-[#102a3a]",
  donut: "relative grid h-[154px] w-[154px] place-content-center rounded-full bg-[conic-gradient(#079b60_var(--billable),#f5d994_0)] after:absolute after:inset-[18px] after:rounded-full after:bg-white after:content-[''] [&_strong]:relative [&_strong]:z-[1] [&_strong]:text-center [&_strong]:text-[27px] [&_span]:relative [&_span]:z-[1] [&_span]:text-center [&_span]:text-[9px] [&_span]:text-[#6c7d89]",
  green: "bg-[#079b60]",
  amber: "bg-[#f2ca6f]",
  "report-table-grid": "grid-cols-[minmax(0,1fr)_300px] max-[1180px]:grid-cols-[minmax(0,1fr)_280px] max-[900px]:grid-cols-1",
  "print-card": "max-[900px]:order-first print:hidden [&_ul]:list-none [&_ul]:p-0 [&_li]:flex [&_li]:items-center [&_li]:gap-[7px] [&_li]:py-1.5 [&_li]:text-[10px] [&_li]:text-[#6c7d89] [&_li_svg]:w-[14px] [&_li_svg]:text-[#079b60]",
  "paper-preview": "mx-auto my-[10px] grid h-[165px] w-[132px] place-items-start justify-center gap-3 border border-[#dfe7e9] bg-white p-[22px] shadow-[0_8px_18px_rgba(17,45,55,.08)] [&_svg]:h-[33px] [&_svg]:w-[33px] [&_svg]:text-[#079b60] [&_span]:h-1 [&_span]:w-[75px] [&_span]:bg-[#dfe6e7] [&_i]:h-[38px] [&_i]:w-[70px] [&_i]:bg-[linear-gradient(90deg,#079b60_30%,#dfe9e6_30%_40%,#276bd5_40%_60%,#dfe9e6_60%)]",
  "employee-report": "mt-[14px] flex items-center justify-between [&>div]:grid [&_span]:text-[10px] [&_span]:text-[#6c7d89] [&>span]:text-lg [&>span]:font-extrabold",
  positive: "text-[#079b60]",
  negative: "text-[#e54845]",
  "leave-layout": "grid grid-cols-[390px_minmax(0,1fr)] gap-[14px] max-[900px]:grid-cols-1",
  "leave-form": "self-start p-5",
  helper: "mt-3 flex items-start gap-[7px] text-[10px] leading-[1.8] text-[#6c7d89] [&_svg]:mt-0.5 [&_svg]:w-[14px] [&_svg]:flex-none",
  "settings-layout": "grid grid-cols-[250px_minmax(0,1fr)] gap-[26px] max-[900px]:grid-cols-1",
  "settings-menu": "self-start p-[10px] max-[900px]:flex max-[900px]:overflow-x-auto [&_button]:flex [&_button]:min-h-[52px] [&_button]:w-full [&_button]:items-center [&_button]:gap-[11px] [&_button]:rounded-[10px] [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-[13px] [&_button]:font-semibold [&_button]:text-[#102a3a] [&_button.active]:bg-[#edf9f4] [&_button.active]:text-[#079b60] max-[900px]:[&_button]:min-w-max",
  "settings-content": "grid grid-cols-2 gap-3 max-[620px]:grid-cols-1",
  "settings-card": "p-5",
  "restore-card": "col-span-full max-[620px]:col-auto",
  "work-settings": "col-span-full max-[620px]:col-auto",
  "storage-list": "m-0 [&>div]:flex [&>div]:justify-between [&>div]:gap-[10px] [&>div]:py-2 [&_dt]:text-[10px] [&_dt]:text-[#6c7d89] [&_dd]:m-0 [&_dd]:text-[11px]",
  "storage-meter": "mb-[15px] mt-2 [&>i]:my-2 [&>i]:block [&>i]:h-[7px] [&>i]:overflow-hidden [&>i]:rounded-[10px] [&>i]:bg-[#e8edef] [&>i>b]:block [&>i>b]:h-full [&>i>b]:rounded-[inherit] [&>i>b]:bg-[#079b60] [&_span]:text-[9px] [&_span]:text-[#6c7d89]",
  "drop-zone": "relative grid min-h-[125px] place-items-center content-center rounded-xl border-[1.5px] border-dashed border-[#079b60] bg-[#fbfefc] text-center text-[#079b60] [&>svg]:h-[25px] [&>svg]:w-[25px] [&_span]:text-[9px] [&_span]:text-[#6c7d89] [&_input]:absolute [&_input]:inset-0 [&_input]:h-full [&_input]:cursor-pointer [&_input]:opacity-0",
  "import-preview": "mt-3 grid gap-[9px] rounded-[10px] border border-[#bde2d4] bg-[#edf9f4] p-3 text-[11px] [&_strong]:flex [&_strong]:gap-[7px] [&_strong]:text-[#079b60]",
  "danger-zone": "col-span-full flex items-center justify-between gap-5 border-[#ffd0cb] bg-[#fffafa] max-[620px]:col-auto max-[620px]:items-stretch max-[620px]:flex-col [&>div]:flex [&>div]:items-center [&>div]:gap-[11px] [&>div>svg]:h-7 [&>div>svg]:w-7 [&>div>svg]:text-[#e54845] [&>div>div]:grid [&_span]:text-[10px] [&_span]:text-[#6c7d89]",
  "empty-state": "grid min-h-[145px] place-content-center justify-items-center gap-[5px] text-center text-[#6c7d89] [&_svg]:h-8 [&_svg]:w-8 [&_svg]:text-[#a9b8be] [&_strong]:text-[#102a3a] [&_span]:text-[10px]",
  compact: "min-h-[90px]",
  large: "col-span-full min-h-[290px]",
  "app-footer": "mx-auto flex min-h-12 max-w-[1510px] items-center justify-between gap-5 rounded-xl border border-[#dfe7e9] bg-white/80 px-4 text-[9px] text-[#6c7d89] [&_span]:flex [&_span]:items-center [&_span]:gap-1.5 [&_svg]:w-[15px] [&_svg]:text-[#079b60] max-[900px]:mb-[76px] max-[620px]:flex-col max-[620px]:items-start max-[620px]:py-[10px] print:hidden",
  toast: "fixed left-1/2 top-[22px] z-[1000] flex -translate-x-1/2 items-center gap-2 rounded-xl border border-[#bce2d3] bg-[#effaf5] px-[17px] py-[11px] text-xs font-bold text-[#087f50] shadow-[0_18px_50px_rgba(17,45,55,.16)]",
  onboarding: "fixed inset-0 z-[500] overflow-y-auto bg-[#fbfdfc]",
  "onboarding-head": "flex h-[88px] items-center justify-between border-b border-[#dfe7e9] px-[42px] max-[620px]:px-4",
  "wizard-shell": "mx-auto my-8 max-w-[1130px] px-6 max-[620px]:mt-[18px] max-[620px]:px-[14px]",
  "wizard-steps": "mx-auto mb-[42px] grid grid-cols-4 [&>div]:relative [&>div]:grid [&>div]:place-items-center [&>div]:gap-[7px] [&>div]:text-[#6c7d89] [&>div:not(:last-child)]:after:absolute [&>div:not(:last-child)]:after:right-1/2 [&>div:not(:last-child)]:after:top-[19px] [&>div:not(:last-child)]:after:-z-[1] [&>div:not(:last-child)]:after:h-[3px] [&>div:not(:last-child)]:after:w-full [&>div:not(:last-child)]:after:bg-[#e3e9ea] [&_span]:grid [&_span]:h-10 [&_span]:w-10 [&_span]:place-items-center [&_span]:rounded-full [&_span]:border [&_span]:border-[#dfe7e9] [&_span]:bg-white [&_span]:text-[#102a3a] [&_.active]:text-[#079b60] [&_.active_span]:border-[#079b60] [&_.active_span]:bg-[#079b60] [&_.active_span]:text-white [&_.done_span]:border-[#079b60] [&_.done_span]:bg-[#079b60] [&_.done_span]:text-white max-[620px]:mb-6 max-[620px]:[&_small]:hidden",
  "wizard-page": "min-h-[520px] text-center [&_h1]:mb-[7px] [&_h1]:mt-0 [&_h1]:text-[clamp(28px,3vw,40px)] [&>p]:mb-[34px] [&>p]:mt-0 [&>p]:text-[#6c7d89] [&>label]:mx-auto [&>label]:my-[35px] [&>label]:max-w-[500px] [&>label]:text-right max-[900px]:min-h-0 max-[620px]:[&_h1]:text-[27px]",
  "wizard-logo": "mx-auto mb-5 mt-[70px] grid h-[82px] w-[82px] place-items-center rounded-3xl bg-[#edf9f4] text-[#079b60] [&_svg]:h-[46px] [&_svg]:w-[46px]",
  "mode-grid": "grid grid-cols-3 gap-[26px] max-[900px]:grid-cols-1 max-[620px]:gap-[10px] [&>button]:relative [&>button]:min-h-[330px] [&>button]:rounded-[17px] [&>button]:border [&>button]:border-[#dfe7e9] [&>button]:bg-white [&>button]:p-[30px] [&>button]:text-center [&>button]:text-[#102a3a] [&>button.selected]:border-2 [&>button.selected]:border-[#079b60] [&>button.selected]:bg-[linear-gradient(145deg,#fff_45%,#effaf5)] [&>button>i]:block [&>button>i]:text-[#657883] [&>button.selected>i]:text-[#079b60] [&>button>i_svg]:mx-auto [&>button>i_svg]:mb-[30px] [&>button>i_svg]:mt-[15px] [&>button>i_svg]:h-[66px] [&>button>i_svg]:w-[66px] [&>button>strong]:text-[22px] [&_ul]:mx-auto [&_ul]:mb-0 [&_ul]:mt-[22px] [&_ul]:grid [&_ul]:list-none [&_ul]:gap-[9px] [&_ul]:p-0 [&_ul]:text-[13px] [&_ul]:text-[#6c7d89] [&_li]:before:ml-[9px] [&_li]:before:text-[#079b60] [&_li]:before:content-['•'] max-[900px]:[&>button]:min-h-[220px] max-[620px]:[&>button]:min-h-[180px] max-[620px]:[&>button]:p-[18px] max-[620px]:[&>button>i_svg]:mx-auto max-[620px]:[&>button>i_svg]:mb-3 max-[620px]:[&>button>i_svg]:mt-[3px] max-[620px]:[&>button>i_svg]:h-[45px] max-[620px]:[&>button>i_svg]:w-[45px] max-[620px]:[&_ul]:mt-[9px] max-[620px]:[&_ul]:text-[11px]",
  selected: "",
  "mode-check": "absolute right-5 top-5 grid h-8 w-8 place-items-center rounded-full bg-[#079b60] text-white",
  "privacy-callout": "mx-auto my-[30px] flex max-w-[610px] items-center gap-[13px] rounded-xl border border-[#c9e9dd] bg-[#edf9f4] p-[18px] text-right [&_svg]:h-7 [&_svg]:w-7 [&_svg]:text-[#079b60] [&_div]:grid [&_span]:text-[11px] [&_span]:text-[#6c7d89]",
  "wizard-actions": "flex justify-between border-t border-[#dfe7e9] pt-[18px]",
  "month-layout": "mb-[18px] grid grid-cols-[minmax(0,1.55fr)_minmax(280px,.45fr)] gap-[18px] max-[900px]:grid-cols-1",
  "month-calendar": "p-[22px] max-[620px]:p-[14px]",
  "weekly-chart": "flex flex-col p-[22px] max-[620px]:p-[14px]",
  "month-calendar-head": "mb-[18px] grid grid-cols-[auto_1fr_auto] items-center gap-4 [&>div]:text-center [&_h2]:m-0 [&_h2]:text-[19px] [&_span]:mt-1 [&_span]:block [&_span]:text-[11px] [&_span]:text-[#6c7d89]",
  "month-weekdays": "mb-[7px] grid grid-cols-7 gap-[7px] [&_span]:text-center [&_span]:text-[11px] [&_span]:font-bold [&_span]:text-[#6c7d89] max-[620px]:gap-1",
  "month-cells": "grid grid-cols-7 gap-[7px] [&_button]:relative [&_button]:flex [&_button]:min-h-[68px] [&_button]:flex-col [&_button]:items-start [&_button]:justify-between [&_button]:rounded-[13px] [&_button]:border [&_button]:border-[#dfe7e9] [&_button]:bg-[#fbfdfc] [&_button]:p-2 [&_button]:text-[#102a3a] [&_button:hover]:border-[#8cc9b4] [&_button:hover]:bg-[#f2faf7] [&_button.outside]:opacity-30 [&_button.today]:shadow-[inset_0_0_0_2px_#079b60] [&_button_small]:text-[9px] [&_button_small]:text-[#6c7d89] [&_button>i]:absolute [&_button>i]:left-2 [&_button>i]:top-[9px] [&_button>i]:h-[7px] [&_button>i]:w-[7px] [&_button>i]:rounded-full max-[620px]:gap-1 max-[620px]:[&_button]:min-h-[52px] max-[620px]:[&_button]:p-1.5 max-[620px]:[&_button_small]:hidden",
  outside: "opacity-30",
  today: "shadow-[inset_0_0_0_2px_#079b60]",
  complete: "border-[#b9e2d2] bg-[#edf9f4] [&>i]:bg-[#19a36c]",
  deficit: "border-[#f0dab5] bg-[#fff8ed] [&>i]:bg-[#e59d2d]",
  partial: "border-[#f0dab5] bg-[#fff8ed] [&>i]:bg-[#e59d2d]",
  leave: "border-[#cbd8fa] bg-[#eef3ff] [&>i]:bg-[#617fd5]",
  holiday: "border-[#ddd6eb] bg-[#f4f2f8] [&>i]:bg-[#8764b2]",
  "calendar-legend": "mt-[15px] flex flex-wrap gap-[15px] text-[10px] text-[#6c7d89] [&_span]:flex [&_span]:items-center [&_span]:gap-1.5 [&_i]:h-2 [&_i]:w-2 [&_i]:rounded-full max-[620px]:gap-[9px]",
  "weekly-bars": "my-[25px] grid h-[270px] grid-cols-7 items-end gap-2 [&>div]:grid [&>div]:h-full [&>div]:grid-rows-[25px_1fr_20px] [&>div]:gap-[5px] [&>div]:text-center [&_span]:text-[9px] [&_span]:text-[#6c7d89] [&_small]:text-[9px] [&_small]:text-[#6c7d89] [&_i]:flex [&_i]:h-full [&_i]:items-end [&_i]:justify-center [&_i]:rounded-lg [&_i]:bg-[#f1f6f4] [&_i]:p-[3px] [&_b]:block [&_b]:w-full [&_b]:rounded-md [&_b]:bg-gradient-to-b [&_b]:from-[#31b47e] [&_b]:to-[#16875b] max-[900px]:h-[210px]",
  "month-table": "mb-[18px]",
  "manual-entry-form": "mb-[18px] p-5 [&_.panel-head]:mb-4",
  "check-field": "flex min-h-11 items-center gap-[9px] self-end text-[#102a3a] [&_input]:h-[18px] [&_input]:w-[18px] [&_input]:accent-[#079b60]",
};

export function tw(...values: Token[]) {
  const tokens = values
    .filter(Boolean)
    .flatMap((value) => String(value).split(/\s+/))
    .filter(Boolean);
  return cn(tokens.map((token) => styles[token] ?? token));
}